### ISSUE TITLE
cpsswarm_msgs fails to build on kinetic

### ISSUE THREAD

**Issue by tfoote** [cpswarm/cpswarm_msgs#1]
It appears to have an invalid dependency. http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__cpswarm_msgs__ubuntu_xenial_amd64__binary/5/console

```
15:12:47 # BEGIN SUBSECTION: append build timestamp
15:12:47 Invoking 'debchange -v 1.1.0-1xenial-20200127-231247+0000 -p -D xenial -u high -m Append timestamp when binarydeb was built.' in '/tmp/binarydeb/ros-kinetic-cpswarm-msgs-1.1.0'
15:12:47 # END SUBSECTION
15:12:49 Looking for the '.dsc' file of package 'ros-kinetic-cpswarm-msgs' with version '1.1.0-1'
15:12:50 Traceback (most recent call last):
15:12:50   File "/usr/lib/python3/dist-packages/apt/cache.py", line 259, in __getitem__
15:12:50     return self._weakref[key]
15:12:50   File "/usr/lib/python3.5/weakref.py", line 131, in __getitem__
15:12:50     o = self.data[key]()
15:12:50 KeyError: 'ros-kinetic-swarmros'
15:12:50 
15:12:50 During handling of the above exception, another exception occurred:
15:12:50 
15:12:50 Traceback (most recent call last):
15:12:50   File "/usr/lib/python3/dist-packages/apt/cache.py", line 263, in __getitem__
15:12:50     rawpkg = self._cache[key]
15:12:50 KeyError: 'ros-kinetic-swarmros'
15:12:50 
15:12:50 During handling of the above exception, another exception occurred:
15:12:50 
15:12:50 Traceback (most recent call last):
15:12:50   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 166, in <module>
15:12:50     main()
15:12:50   File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 85, in main
15:12:50     apt_cache, debian_pkg_names)
15:12:50   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 154, in get_binary_package_versions
15:12:50     pkg = apt_cache[debian_pkg_name]
15:12:50   File "/usr/lib/python3/dist-packages/apt/cache.py", line 265, in __getitem__
15:12:50     raise KeyError('The cache has no package named %r' % key)
15:12:50 KeyError: "The cache has no package named 'ros-kinetic-swarmros'"
15:12:50 Build step 'Execute shell' marked build as failure
15:12:50 $ ssh-agent -k
15:12:50 unset SSH_AUTH_SOCK;
```

**Comment by tfoote** [comment]
Dependency is failing to build and was removed in: https://github.com/ros/rosdistro/pull/23586 that's why it's missing. Re: https://github.com/amilankovich-slab/swarmros/issues/1
